config/routes.rb
Rails.application.routes.draw do

  resources :orders

  resources :line_items

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :carts

  resources :categories do
    resources :collections
  end

  resources :collections do
    resources :products
  end

  match '/import', to: 'import#index', via: 'get'
  match '/import/show', to: 'import#show', via: 'get'
  root 'static#home'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
	has_many :products, dependent: :destroy
	has_many :connections
	has_many :categories, through: :connections

	 paginates_per 3
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    #@collections = Collection.all
    @collections = Collection.order(:name).page params[:page]
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params[:collection]
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/_sidebar.html.erb
						<aside class="col-lg-3 col-md-3 col-sm-3">
														<figure class="widget shadow r_corners wrapper m_bottom_30">
								<figcaption>
									<h3 class="color_light">Все категории</h3>
								</figcaption>
								<div class="widget_content">
									<!--Categories list-->
									<ul class="categories_list">
										<li class="active">
											<a href="#" class="f_size_large scheme_color d_block relative">
												<b>Плитка</b>
												<span class="bg_light_color_1 r_corners f_right color_dark talign_c"></span>
											</a>
											<!--second level-->
											<ul>
												<li class="active">
													<a href="#" class="d_block f_size_large color_dark relative">
														Настенная плитка
													</a>
													<a href="#" class="d_block f_size_large color_dark relative">
														Напольная плитка
													</a>
													<a href="#" class="d_block f_size_large color_dark relative">
														Плита для кухни
													</a>
													<a href="#" class="d_block f_size_large color_dark relative">
														Восточные коллекции
													</a>
													<a href="#" class="d_block f_size_large color_dark relative">
														Для бассеина
													</a>
												</li>
											</ul>
										</li>
										<li class="active">
											<a href="#" class="f_size_large scheme_color d_block relative">
												<b>Керамогранит</b>
												<span class="bg_light_color_1 r_corners f_right color_dark talign_c"></span>
											</a>
											<!--second level-->
											<ul>
												<li class="active">
													<a href="#" class="d_block f_size_large color_dark relative">
														Матовый
													</a>
													<a href="#" class="d_block f_size_large color_dark relative">
														Полированый
													</a>
													<a href="#" class="d_block f_size_large color_dark relative">
														Полуполированный
													</a>
													<a href="#" class="d_block f_size_large color_dark relative">
														Структурированый
													</a>
												</li>
											</ul>
										</li>
									</ul>
								</div>
							</figure>
								
						</aside>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Collections</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_collection_path %>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
			<style type="text/css">
				.category_grid .product_item{
					float: left;
				}
			</style>
			<% provide(:title,   	 @collection.meta_title) %>
			<% provide(:description, @collection.meta_description) %>
			<% provide(:keywords, 	 @collection.meta_keywords) %>
			<div class="page_content_offset">
				<div class="container">
					<div class="row clearfix">
						
						<!--right column-->
						<%= render 'sidebar' %>

						<!--left content column-->
						<section class="col-lg-9 col-md-9 col-sm-9">
							<h2 class="tt_uppercase color_dark m_bottom_25"><%= @collection.name %></h2>
							<div class="clearfix m_bottom_40">
									<div class="photoframe f_left shadow wrapper m_right_30 m_sm_bottom_5 m_sm_right_20 m_xs_bottom_15 f_xs_none d_xs_inline_b">
										<img class="tr_all_long_hover" src="/images/category_img_7.jpg" alt="">
									</div>
									<p class="m_bottom_10">Бренд: <%= @collection.brand %> </p>
									<p class="m_bottom_10">Страна: <%= @collection.country %> </p>
									<p class="m_bottom_10">Размер: <%= @collection.size %> </p>
							</div>

							
							<hr />
							<!--products-->
							<section class="products_container category_grid clearfix m_bottom_15">
								<!--product item-->
								<% @collection.products.each do |product| %>
									<div class="product_item hit w_xs_full">
										<figure class="r_corners photoframe type_2 t_align_c tr_all_hover shadow relative">
											<!--product preview-->
											<a href="#" class="d_block relative wrapper pp_wrap m_bottom_15">
												<img src="/images/product_img_1.jpg" class="tr_all_hover" alt="">
												<span role="button" data-popup="#quick_view_product" class="button_type_5 box_s_none color_light r_corners tr_all_hover d_xs_none">Предосмотр</span>
											</a>
											<!--description and price of product-->
											<figcaption>
												<h5 class="m_bottom_10">
												<%= link_to product.name, collection_product_path(@collection , product), class: "color_dark" %>
												</h5>
												
												<p class="scheme_color f_size_large m_bottom_15"><%= product.price %> р.</p>	
												<!--<button class="button_type_4 bg_scheme_color r_corners tr_all_hover color_light mw_0 m_bottom_15">Add to Cart</button>-->
												<%= button_to 'Купить', line_items_path(product_id: product), class: 'button_type_4 bg_scheme_color r_corners tr_all_hover color_light mw_0 m_bottom_15'
												 %>
											</figcaption>
										</figure>
									</div>
								<% end %>
							</section>
							
							<hr class="m_bottom_10 divider_type_3">
							
						</section>
						
					</div>
				</div>
			</div>

app/views/collections/test.html.erb
							<div class="col-lg-4 col-md-4 col-sm-4">
									<div class="photoframe type_2 shadow r_corners f_left f_sm_none d_xs_inline_b product_single_preview relative m_right_30 m_bottom_5 m_sm_bottom_20 m_xs_right_0 w_mxs_full">
								<div class="relative d_inline_b m_bottom_10 qv_preview d_xs_block">
									<img id="zoom_image" src="/images/product_img_1.jpg" data-zoom-image="images/preview_zoom_1.jpg" class="tr_all_hover" alt="">
									<a href="images/preview_zoom_1.jpg" class="d_block button_type_5 r_corners tr_all_hover box_s_none color_light p_hr_0">
										<i class="fa fa-expand"></i>
									</a>
								</div>	
								<div class="relative qv_carousel_wrap">
									<button class="button_type_11 bg_light_color_1 t_align_c f_size_ex_large bg_cs_hover r_corners d_inline_middle bg_tr tr_all_hover qv_btn_single_prev">
										<i class="fa fa-angle-left "></i>
									</button>
									<ul class="qv_carousel_single d_inline_middle" >
										<a href="#" data-image="images/quick_view_img_7.jpg" data-zoom-image="images/preview_zoom_1.jpg"><img src="/images/quick_view_img_10.jpg" alt=""></a>
									</ul>
									<button class="button_type_11 bg_light_color_1 t_align_c f_size_ex_large bg_cs_hover r_corners d_inline_middle bg_tr tr_all_hover qv_btn_single_next">
										<i class="fa fa-angle-right "></i>
									</button>
								</div>
							</div>

							<div class="col-lg-4 col-md-4 col-sm-4">
									<p>zzz</p>
							</div>