config/routes.rb
Rails.application.routes.draw do

  resources :orders

  resources :line_items

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :carts

  resources :categories do
    resources :collections
  end

  resources :collections do
    resources :products
  end

  match '/import', to: 'import#index', via: 'get'
  match '/import/show', to: 'import#show', via: 'get'
  root 'static#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :categories
	belongs_to :category
	has_many :connections
	has_many :collections, through: :connections

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params[:category]
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<style type="text/css">
	.category_grid .product_item{
		clear: none;
		float: left;
	}
</style>
<% provide(:title, @category.meta_title) %>
<% provide(:description, @category.meta_description) %>
<% provide(:keywords, @category.meta_keywords) %>
<div class="page_content_offset">
				<div class="container">
					<div class="row clearfix">
						<!--left content column-->
						<%= render '/collections/sidebar' %>
						<section class="col-lg-9 col-md-9 col-sm-9">
							<h2 class="tt_uppercase color_dark m_bottom_25"><%= @category.name %></h2>
							<div class="clearfix m_bottom_40">
									<div class="photoframe f_left shadow wrapper m_right_30 m_sm_bottom_5 m_sm_right_20 m_xs_bottom_15 f_xs_none d_xs_inline_b">
										<img class="tr_all_long_hover" src="/images/category_img_7.jpg" alt="">
									</div>
									<p class="m_bottom_10">Здесь описание категории</p>
							</div>

							
							<hr />
							<!--sort-->
							<!--products-->
														<!--categories nav-->
							<nav class="m_bottom_40">
								<ul class="products_container category_grid clearfix m_bottom_15 isotope">
									<% if  @category.collections.count > 0 %>
										<% @category.collections.each do |collection| %>
											<div class="product_item hit w_xs_full">
												<figure class="r_corners photoframe type_2 t_align_c tr_all_hover shadow relative">
													<!--product preview-->
													<a href="#" class="d_block relative wrapper pp_wrap m_bottom_15">
														<img src="/images/product_img_1.jpg" class="tr_all_hover" alt="">
														<!--<span role="button" data-popup="#quick_view_product" class="button_type_5 box_s_none color_light r_corners tr_all_hover d_xs_none">Quick View</span> -->
													</a>
													<!--description and price of product-->
													<figcaption class="m_bottom_10">
														<h5 class="m_bottom_10"><%= link_to collection.name, category_collection_path(@category , collection) %></h5>	
														<p class="f_left f_size_small d_block r_corners">Бренд: <b class="color_dark"><%= collection.brand %></b></p><br/>
														<p class="f_left f_size_small d_block r_corners">Страна: <b class="color_dark"><%= collection.country %></b></p><br/>
														<p class="f_left f_size_small d_block r_corners">Размер: <b class="color_dark"><%= collection.size %></b></p>
													</figcaption>
												</figure>
											</div>

										<% end %>
									<% else   @category.categories.each do |category| %>
											<div class="product_item hit w_xs_full">
												<figure class="r_corners photoframe type_2 t_align_c tr_all_hover shadow relative">
													<!--product preview-->
													<a href="#" class="d_block relative wrapper pp_wrap m_bottom_15">
														<img src="/images/product_img_1.jpg" class="tr_all_hover" alt="">
														<!--<span role="button" data-popup="#quick_view_product" class="button_type_5 box_s_none color_light r_corners tr_all_hover d_xs_none">Quick View</span> -->
													</a>
													<!--description and price of product-->
													<figcaption class="m_bottom_10">
														<h5 class="m_bottom_10"><%= link_to category.name, category_path(category) %></h5>	
													</figcaption>
												</figure>
											</div>
											<% end %>
									<% end %>
								</ul>
							</nav>	
							 <%= paginate @collections %> 
							<hr class="m_bottom_10 divider_type_3">
							<div class="row clearfix m_bottom_15 m_xs_bottom_30">
								<div class="col-lg-7 col-md-7 col-sm-8 m_xs_bottom_10">
									<p class="d_inline_middle f_size_medium d_xs_block m_xs_bottom_5">Results 1 - 5 of 45</p>
									<p class="d_inline_middle f_size_medium m_left_20 m_xs_left_0">Show:</p>
									<!--show items per page select-->
									<div class="custom_select f_size_medium relative d_inline_middle m_left_5">
										<div class="select_title r_corners relative color_dark">9</div>
										<ul class="select_list d_none"></ul>
										<select name="show_second">
											<option value="Manufacture 1">6</option>
											<option value="Manufacture 2">3</option>
											<option value="Manufacture 3">1</option>
										</select>
									</div>
									<p class="d_inline_middle f_size_medium m_left_5">items per page</p>
								</div>
								<div class="col-lg-5 col-md-5 col-sm-4 t_align_r t_xs_align_l">
									<!--pagination-->
									<a role="button" href="#" class="button_type_10 color_dark d_inline_middle bg_cs_hover bg_light_color_1 t_align_c tr_delay_hover r_corners box_s_none"><i class="fa fa-angle-left"></i></a>
									<ul class="horizontal_list clearfix d_inline_middle f_size_medium m_left_10">
										<li class="m_right_10"><a class="color_dark" href="#">1</a></li>
										<li class="m_right_10"><a class="scheme_color" href="#">2</a></li>
										<li class="m_right_10"><a class="color_dark" href="#">3</a></li>
									</ul>
									<a role="button" href="#" class="button_type_10 color_dark d_inline_middle bg_cs_hover bg_light_color_1 t_align_c tr_delay_hover r_corners box_s_none"><i class="fa fa-angle-right"></i></a>
								</div>
							</div>
						</section>
						<!--right column-->
					</div>
				</div>
			</div>