config/routes.rb
Rails.application.routes.draw do

  resources :orders

  resources :line_items

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :carts

  resources :categories do
    resources :collections
  end

  resources :collections do
    resources :products
  end

  match '/import', to: 'import#index', via: 'get'
  match '/import/show', to: 'import#show', via: 'get'
  root 'static#home'

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :collection
	has_many :line_items

	before_destroy :ensure_not_referenced_by_any_line_item

	private

	def ensure_not_referenced_by_any_line_item
		if line_items.empty? 
			return true
		else
			errors.add(:base, 'существуют товарные позиции')
			return false
		end
		
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params[:product]
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
			<% provide(:title,   	 @product.meta_title) %>
			<% provide(:description, @product.meta_description) %>
			<% provide(:keywords, 	 @product.meta_keywords) %>
			<div class="page_content_offset">
				<div class="container">
					<div class="clearfix m_bottom_30 t_xs_align_c">
						<div class="photoframe type_2 shadow r_corners f_left f_sm_none d_xs_inline_b product_single_preview relative m_right_30 m_bottom_5 m_sm_bottom_20 m_xs_right_0 w_mxs_full">
							<div class="relative d_inline_b m_bottom_10 qv_preview d_xs_block">
								<img id="zoom_image" src="/images/quick_view_img_7.jpg" data-zoom-image="/images/preview_zoom_1.jpg" class="tr_all_hover" alt="">
								<a href="/images/preview_zoom_1.jpg" class="d_block button_type_5 r_corners tr_all_hover box_s_none color_light p_hr_0">
									<i class="fa fa-expand"></i>
								</a>
							</div>
							<!--carousel-->
							<div class="relative qv_carousel_wrap">
								<button class="button_type_11 bg_light_color_1 t_align_c f_size_ex_large bg_cs_hover r_corners d_inline_middle bg_tr tr_all_hover qv_btn_single_prev">
									<i class="fa fa-angle-left "></i>
								</button>
								<ul class="qv_carousel_single d_inline_middle">
									<a href="#" data-image="/images/quick_view_img_7.jpg" data-zoom-image="/images/preview_zoom_1.jpg"><img src="/images/quick_view_img_10.jpg" alt=""></a>
									<a href="#" data-image="/images/quick_view_img_8.jpg" data-zoom-image="/images/preview_zoom_2.jpg"><img src="/images/quick_view_img_11.jpg" alt=""></a>
									<a href="#" data-image="/images/quick_view_img_9.jpg" data-zoom-image="/images/preview_zoom_3.jpg"><img src="/images/quick_view_img_12.jpg" alt=""></a>
									<a href="#" data-image="/images/quick_view_img_16.jpg" data-zoom-image="/images/preview_zoom_4.jpg"><img src="/images/quick_view_img_13.jpg" alt=""></a>
									<a href="#" data-image="/images/quick_view_img_17.jpg" data-zoom-image="/images/preview_zoom_5.jpg"><img src="/images/quick_view_img_14.jpg" alt=""></a>
									<a href="#" data-image="/images/quick_view_img_18.jpg" data-zoom-image="/images/preview_zoom_6.jpg"><img src="/images/quick_view_img_15.jpg" alt=""></a>
								</ul>
								<button class="button_type_11 bg_light_color_1 t_align_c f_size_ex_large bg_cs_hover r_corners d_inline_middle bg_tr tr_all_hover qv_btn_single_next">
									<i class="fa fa-angle-right "></i>
								</button>
							</div>
						</div>
						<div class="p_top_10 t_xs_align_l">
							<!--description-->
							<h2 class="color_dark fw_medium m_bottom_10"><%= @product.name %></h2>
							<div class="m_bottom_10">
							</div>
							<hr class="m_bottom_10 divider_type_3">
							<table class="description_table m_bottom_10">
								<tr>
									<td>Категория</td>
									<td><%= @product.category %></td>
								</tr>
								<tr>
									<td>Артикул</td>
									<td><%= @product.code %></td>
								</tr>
								<tr>
									<td>Availability:</td>
									<td><span class="color_green">in stock</span> 20 item(s)</td>
								</tr>
								<tr>
									<td>Product Code:</td>
									<td>PS06</td>
								</tr>
							</table>
							<hr class="divider_type_3 m_bottom_10">
							<div class="m_bottom_15">
								<span class="v_align_b f_size_big m_left_5 scheme_color fw_medium"><%= @product.price %>р.  / <%= @product.edizm %></span>
							</div>
							<div class="d_ib_offset_0 m_bottom_20">
								<%= button_to 'Купить', line_items_path(product_id: @product.id), class: 'button_type_12 r_corners bg_scheme_color color_light tr_delay_hover d_inline_b f_size_large'
												 %>
							</div>
						</div>
					</div>
					<!--tabs-->
					<div class="tabs m_bottom_45">
						<!--tabs navigation-->
						<nav>
							<ul class="tabs_nav horizontal_list clearfix">
								<li class="f_xs_none"><a href="#tab-1" class="bg_light_color_1 color_dark tr_delay_hover r_corners d_block">Характеристики</a></li>
							</ul>
						</nav>
						<section class="tabs_content shadow r_corners">
							<div id="tab-1">
								<p>Название: <%= @product.name %></p>
								<p>Артикул:  <%= @product.code %></p>
								<p>Область применения: <%= @product.field_of_application_list %></p>
								<p>Место в коллекции: <%= @product.place_in_the_collection %></p>
								<p>Минимальная партия: <%= @product.minpart %></p>
								p>cratnost: <%= @product.cratnost %></p>
								<p>weight: <%= @product.weight %></p>
								<p>Размер: <%= @product.size %></p>
								<p>Назначение: <%= @product.architectural_surface %></p>
								<p>base_value: <%= @product.base_value %></p>
								<p>Цвет: <%= @product.cover_value %></p>
								<p>Вид поверхности: <%= @product.surface_alue %></p>
								<p>image: <%= @product.image %></p>
								<p>Наличие: <%= @product.ballance %></p>
								<p>В наличии: <%= @product.ballance_count %></p>
								<p>Категория: <%= @product.category %></p>
								<p>Дизайн, стилистика: <%= @product.design_value %></p>
								<p>Морозостойкость: <%= @product.frost_hardiness %></p>
								<p>ректифицированная: <%= @product.rectified %></p>

							</div>
						</section>
					</div>
					
				</div>
			</div>